### ISSUE TITLE
期名称导致脚本崩溃

### ISSUE THREAD

**Issue by ghost** [cgcel/visitopia-dl#1]
我在下载「100个职业告白」节目时，下载到第七期就出现了异常，脚本停止运作。
详细报错如下：
```
Traceback (most recent call last):
  File "D:\archive\Podcast\visitopia-dl\visitopia-dl.py", line 36, in <module>
    main()
  File "D:\archive\Podcast\visitopia-dl\visitopia-dl.py", line 30, in main
    VISTOPIA().download_all(url=url)
  File "D:\archive\Podcast\visitopia-dl\visitopia.py", line 142, in download_all
    with open('{}/{}.{}'.format(self.title, media_title, media_type), 'wb') as f:
OSError: [Errno 22] Invalid argument: '100个职业告白/07 单口喜剧演员周奇墨："燃烧”自己，是我的创作方式.mp3'
```

节目链接：https://shop.vistopia.com.cn/detail?id=64

期链接：https://shop.vistopia.com.cn/article?article_id=155900

**Comment by velviagris** [comment]
感谢使用, 经过确认是因为文章的标题包含了特殊字符导致mp3文件无法创建, 已经修复
